
development:
  sessions:
    default:
      database: lettersmashr_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: lettersmashr_test
      hosts:
        - localhost:27017